runtime: nodejs22

automatic_scaling:
  max_instances: 4
  max_idle_instances: 4
  target_cpu_utilization: 0.92
  target_throughput_utilization: 0.92
  max_concurrent_requests: 800

env_variables:
  NITRO_PORT: "8080"
  NITRO_HOST: "0.0.0.0"

handlers:
  # PWA files
  - url: /sw.js
    static_files: .output/public/sw.js
    upload: .output/public/sw.js

  # PWA manifest
  - url: /manifest.webmanifest
    static_files: .output/public/manifest.webmanifest
    upload: .output/public/manifest.webmanifest

  # Serve Nuxt build assets directly (faster, bypasses Node)
  - url: /_nuxt
    static_dir: .output/public/_nuxt
  
  # Serve static assets from public directory (images, CSS, etc.)
  - url: /img
    static_dir: .output/public/img
  - url: /css
    static_dir: .output/public/css
  - url: /favicon.ico
    static_files: .output/public/favicon.ico
    upload: .output/public/favicon.ico
  - url: /robots.txt
    static_files: .output/public/robots.txt
    upload: .output/public/robots.txt

  # Serve all other routes through Node.js (catch all)
  - url: /.*
    script: auto