steps:
  # 1. Install dependencies with cache
  - name: node:22
    entrypoint: npm
    args: ["ci"]
    volumes:
      - name: npm-cache
        path: /root/.npm

  # 2. Build Nuxt (generates .output/)
  - name: node:22
    entrypoint: npm
    args: ["run", "build"]
    volumes:
      - name: npm-cache
        path: /root/.npm

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", 'app.yaml', 'cron.yaml']  # , 'index.yaml'
    timeout: "1600s"  # Adjust the timeout as needed

timeout: "2800s"  # Adjust the overall build timeout as needed

options:
  logging: CLOUD_LOGGING_ONLY