steps:
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['install']

  - name: 'node:22'
    entrypoint: 'npm'
    args: ['run', 'build']

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", 'app.yaml']  # , 'cron.yaml', 'index.yaml'
    timeout: "1600s"  # Adjust the timeout as needed

timeout: "2800s"  # Adjust the overall build timeout as needed

options:
  logging: CLOUD_LOGGING_ONLY